apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-gkau
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-gkau@sha256:690dba28074643445d3cf2f0cd8edc011105dc04a3e49fda15252739734fc033
        name: my-nodejs
        resources: {}
status: {}
